### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by Madis0** [Schauweg/TillitBreaks#2]
I suggest adding some options to the mod, including:

- Show durability if full (disabling would imitate vanilla behaviour)
- Show durability number, durability bar, arrow count (separate options for each)
- Font size

I only installed this mod for the arrow counts actually but I am a bit lazy to implement the config myself :D

**Comment by Schauweg** [comment]
Thanks for the great ideas. I added them with the latest commit

**Comment by Madis0** [comment]
I checked the latest version out and
> Show durability if full (disabling would imitate vanilla behaviour)

I actually meant hiding the durability numbers if full, not showing the bar always 😁 Apologies for the bad wording.

**Comment by Schauweg** [comment]
Oh okay, my bad. I'll implement this once I have the time to do :D

**Comment by Schauweg** [comment]
Okay now it should be right 😁
